### ISSUE TITLE
"LLM Chat Completions" section of dashboard cuts off horizontal text overflow.

### ISSUE THREAD

**Issue by zsiegel92** [pydantic/logfire#113]
### Description

In the image below I've covered the actual text, but the prompt gets cut off and this makes the dashboard unusable for what would otherwise be a wonderful convenience.

![image](https://github.com/pydantic/logfire/assets/26341564/abd00b3c-c1d7-4e0c-924e-510a8881efad)

Add a clickable, `...more` button, make this element scrollable, or whatever sounds best to you!

Thanks so much

**Comment by alexmojaki** [comment]
@dmontagu any changes here?

**Comment by dmontagu** [comment]
Sorry for the slow fix here. I've made it so that we add `white-space: pre-wrap` to the CSS for code blocks, which I think will ensure that you get wrapping for content in code blocks like this. @zsiegel92 if that is problematic for other reasons let us know and I could look into making it horizontally-scrollable within the code component, or something like that.

If the same text overflow is happening in other ways (i.e., outside of code blocks), please let us know.

(The fix is not deployed yet, but will be shortly. I will update this message and remove this line once it is deployed.)
