### ISSUE TITLE
So Logfire logs are actually traces?

### ISSUE THREAD

**Issue by astrojuanlu** [pydantic/logfire#293]
### Question

As per title:

https://github.com/pydantic/logfire/blob/770780d4e0f5610bd8cbd596029d0cb1e23f25ae/logfire/_internal/main.py#L654-L670

Asking because I have been exploring OpenTelemetry recently and was disappointed to find that [the client APIs for logging in Python are still in development](https://opentelemetry.io/docs/languages/python/#status-and-releases) and seemingly unstable:

![image](https://github.com/kedro-org/kedro/assets/316517/372ada41-60b2-45d1-a98f-272247732695)

**Comment by astrojuanlu** [comment]
So I'd love to understand more whether the decision from Logfire to implement logs as instantaneous traces was a practical one, and if you foresee a different kind of integration when OTel stabilizes. Or maybe nobody cares about logs and traces + metrics is plenty enough observability?

**Comment by samuelcolvin** [comment]
We'll reply in more detail tomorrow, but basically - yes, what we sometimes call "logs" are really traces.

Talking to the otel creators, logs only really exist for backwards compatibility with legacy logging systems in languages.

Traces and metrics are all you need.

**Comment by samuelcolvin** [comment]
Reviewing this, I'm not sure there's much more for me to add.

We could have used span events for "logs" e.g. `logfire.info` calls, but they wouldn't have been sent until the parent spans completes which would be a non-starter.

We could have used otel logs for `logfire.info` etc., but that would have been a lot more work when we were prototyping, and would have caused a significantly different code route for data that's almost identical. All for no user advantage AFAIK.

@astrojuanlu let me know if you have any questions, otherwise we may as well close this.

**Comment by astrojuanlu** [comment]
Not much else to add, thanks! I don't have a problem with the current approach, was curious about the rationale. I'm about to give Logfire a try for the first time, will keep you folks posted :)
